### ISSUE TITLE
get out of savannah

### ISSUE THREAD

**Issue by cbernet** [CERN-PH-CMG/cmg-cmssw#12]
We are migrating to github for issue tracking. 

We still depend on savannah for the publication of the CMG samples. We decided to stop publish information to savannah, and to rely on the sole CMG DB to keep track of our samples. 

Somebody should take care of removing the corresponding code from the CMGTools/Production package.

**Comment by gpetruc** [comment]
I was aware only of the things that are now fixed in the pull request #16.
I'm leaving this open for another few days if there's anything else that people think we have to do related to savannah outside that package (@cbernet @ssekmen: any ideas?)
