### ISSUE TITLE
remove stringbitsets

### ISSUE THREAD

**Issue by cbernet** [CERN-PH-CMG/cmg-cmssw#13]
Nobody's using the stringbitsets, and the stringbitsets definitions don't correspond anymore to the official POG recommendations.

We decided to remove them. 

To do:
- remove the stringbitset C++ and python code from the central CMG packages, and announce this change to everybody so that the people responsible for the various analysis packages can adapt.
- review the code in CMGTools/RootTools/python/physicsobjects, find useful functions (ask the authors of the code which functions are used), and port them to the CMG C++ classes.

**Comment by gpetruc** [comment]
Working on it, implemented the ids for electrons and muons, I'll probably need help for taus and jets.
