### ISSUE TITLE
Localtion of cmsIO module.

### ISSUE THREAD

**Issue by geonmo** [CERN-PH-CMG/cmg-cmssw#15]
Dear experts,
I used cmg package on our local site.(outside CERN)
On CMGTools / Production / python / eostools.py and dataset.py,
These tools need to import cmsIO module. 
However, I can not find cmsIO.py from cmg package.
Where is cmsIO.py module?
Please, let me know this.

Thanks, 
Regards,

**Comment by gpetruc** [comment]
At CERN it seems to be from the CAF tools, the file is in /afs/cern.ch/cms/caf/python/cmsIO.py
I have no idea of how portable it is to other storage systems.

**Comment by vischia** [comment]
Hi, even in lxplus, /afs/cern.ch/cms/caf/python/cmsIO.py is not available anymore.

Yesterday the directory has been emptied:
 drwxr-xr-x. 6 22243 zh 2.0K Jun 12 11:25 python
and now cmsIO.py is in the 
/afs/cern.ch/cms/caf/python.new
and also in
/afs/cern.ch/cms/caf/python.old

Does anyone know which are the caf software plans for that? I mean, can we expect that cmsIO will be put back in its place, or should we just update the path to it to /afs/cern.ch/cms/caf/python.new/ ?

**Comment by vischia** [comment]
(sorry for the spam, I realized it is better to open a new issue, so I did it: https://github.com/CERN-PH-CMG/cmg-cmssw/issues/699 )
