### ISSUE TITLE
Archive / removal of the !(53X) samples

### ISSUE THREAD

**Issue by gitytakahas** [CERN-PH-CMG/cmg-cmssw#151]
Hi all,

As we have discussed in today's meeting, we will consider to archive / remove !(53X) samples.
The list of the samples to be affected is as followings.

https://twiki.cern.ch/twiki/bin/view/Main/Cmgtools

Please have a **careful** look and reply to this thread, if you find any samples to be kept.
The deadline is 5 Dec.

Cheers,
Yuta

**Comment by ssekmen** [comment]
Dear Yuta,

I would be happy if we could keep the following samples for a few more weeks until our analysis is approved:  These are 52X - I am assuming that 53X will be kept.
I will inform you when we are approved, so can delete them.

Thanks.
Sezen

---

On the group space: 

T2tt samples: 

/SMS-8TeV-Pythia6Z_T2tt_mStop-150to475_mLSP-1/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B
/SMS-8TeV-Pythia6Z_T2tt_mStop-500to800_mLSP-1/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B
/SMS-T2tt_mStop-150to350_mLSP-0to250_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B
/SMS-T2tt_mStop-375to475_mLSP-0to375_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B
/SMS-T2tt_mStop-500to650_mLSP-0to225_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B
/SMS-T2tt_mStop-500to650_mLSP-250to550_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B
/SMS-T2tt_mStop-675to800_mLSP-0to275_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B
/SMS-T2tt_mStop-675to800_mLSP-300to700_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B
/SMS-T2tt_mStop-825to900_mLSP-1_and_mLSP-25to800_8TeV-Pythia6Zstar/Summer12-START52_V9_FSIM-v3/AODSIM/V5_B
/SMS-T2tt_mStop-925to1000_mLSP-1_and_mLSP-25to900_8TeV-Pythia6Zstar/Summer12-START52_V9_FSIM-v3/AODSIM/V5_B

T1ttcc old samples

/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-310-325-350-375_mLSP-300/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B  
/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-410-425-450-475_mLSP-400/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B  
/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-510-525-550-575_mLSP-500/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B  
/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-610-625-650-675_mLSP-600/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B  
/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-710-725-750-775_mLSP-700/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B  
/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-810-825-850-875_mLSP-800/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B

---

On the user space: 

T2tt samples: 

/SMS-8TeV-Pythia6Z_T2tt_mStop-150to475_mLSP-1/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-8TeV-Pythia6Z_T2tt_mStop-500to800_mLSP-1/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-T2tt_mStop-150to350_mLSP-0to250_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-T2tt_mStop-375to475_mLSP-0to375_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-T2tt_mStop-500to650_mLSP-0to225_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-T2tt_mStop-500to650_mLSP-250to550_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-T2tt_mStop-675to800_mLSP-0to275_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-T2tt_mStop-675to800_mLSP-300to700_8TeV-Pythia6Z/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-T2tt_mStop-825to900_mLSP-1_and_mLSP-25to800_8TeV-Pythia6Zstar/Summer12-START52_V9_FSIM-v3/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-T2tt_mStop-925to1000_mLSP-1_and_mLSP-25to900_8TeV-Pythia6Zstar/Summer12-START52_V9_FSIM-v3/AODSIM/V5_B/CMGPF_V5_16_0

T1ttcc old samples: 

/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-310-325-350-375_mLSP-300/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-410-425-450-475_mLSP-400/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-510-525-550-575_mLSP-500/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-610-625-650-675_mLSP-600/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-710-725-750-775_mLSP-700/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0
/SMS-MadGraph_Pythia6Zstar_8TeV_T1ttcc_2J_mGo-1000_mStop-810-825-850-875_mLSP-800/Summer12-START52_V9_FSIM-v1/AODSIM/V5_B/CMGPF_V5_16_0

**Comment by gitytakahas** [comment]
Hi all,

Since there is no need to keep !(53X) samples anymore (I was waiting some analysts who might need some datasets), I've archived them. The affected samples are,

https://twiki.cern.ch/twiki/bin/view/Main/Cmgtools
(68TB for group space and 29TB for user space)

The quota now becomes 95% -> 85% (group) and 80 -> 73% (user).

If you want to access these archived files, please see some instructions below
https://github.com/CERN-PH-CMG/cmg-cmssw/issues/51

Issue closed.

Cheers,
Yuta
