### ISSUE TITLE
Transfer Request @ PHYS14 campaign

### ISSUE THREAD

**Issue by gitytakahas** [CERN-PH-CMG/cmg-cmssw#163]
Hi Giovanni,

Good idea to have a separate issue - I made a new one.

> /ZZTo4L_Tune4C_13TeV-powheg-pythia8/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
> /GluGluToHToZZTo4L_M-125_13TeV-powheg-pythia6/Phys14DR-PU20bx25_tsg_PHYS14_25_V1-v1/MINIAODSIM
> /GluGluToHToZZTo4L_M-125_13TeV-powheg-pythia6/Phys14DR-PU40bx25_PHYS14_25_V1-v1/MINIAODSIM

The request is here, 
https://cmsweb.cern.ch/phedex/prod/Request::View?request=429839

Yuta

**Comment by mariadalfonso** [comment]
Hi Yuta.
Can you transfer to the CAF those samples ?

/DYJetsToMuMu_PtZ-180_M-50_13TeV-madgraph/Phys14DR-PU20bx25_tsg_PHYS14_25_V1-v3/MINIAODSIM
/WJetsToLNu_13TeV-madgraph-pythia8-tauola/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM

/QCD_HT_250To500_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1_ext1-v2/MINIAODSIM
/QCD_HT-500To1000_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1_ext1-v1/MINIAODSIM
/TTbarH_M-125_13TeV_amcatnlo-pythia8-tauola/Phys14DR-PU20bx25_tsg_PHYS14_25_V1-v2/MINIAODSIM

/SMS-T1tttt_2J_mGl-1500_mLSP-100_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU40bx25_PHYS14_25_V1-v1/MINIAODSIM
/SMS-T2tt_2J_mStop-650_mLSP-325_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU40bx25_PHYS14_25_V1-v1/MINIAODSIM
/SMS-T2tt_2J_mStop-500_mLSP-325_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU40bx25_PHYS14_25_V1-v1/MINIAODSIM

/DYJetsToMuMu_PtZ-180_M-50_13TeV-madgraph/Spring14miniaod-141029_PU40bx50_PLS170_V6AN2-v1/MINIAODSIM
/ZZTo4L_Tune4C_13TeV-powheg-pythia8/Spring14miniaod-141029_PU40bx50_PLS170_V6AN2-v1/MINIAODSIM

Maria

**Comment by gitytakahas** [comment]
Here it is, 

https://cmsweb.cern.ch/phedex/prod/Request::View?request=430007

**Comment by steggema** [comment]
Hi Yuta,

Can you also transfer the following samples?

/GluGluToHToTauTau_M-125_13TeV-powheg-pythia6/Phys14DR-PU20bx25_tsg_PHYS14_25_V1-v1/MINIAODSIM
/GluGluToHToTauTau_M-125_13TeV-powheg-pythia6/Phys14DR-PU40bx25_PHYS14_25_V1-v2/MINIAODSIM

/VBF_HToTauTau_M-125_13TeV-powheg-pythia6/Phys14DR-PU20bx25_tsg_PHYS14_25_V1-v2/MINIAODSIM
/VBF_HToTauTau_M-125_13TeV-powheg-pythia6/Phys14DR-PU40bx25_PHYS14_25_V1-v1/MINIAODSIM

(/TTbarH_M-125_13TeV_amcatnlo-pythia8-tauola/Phys14DR-PU20bx25_tsg_PHYS14_25_V1-v2/MINIAODSIM) also in Maria’s request
/TTbarH_M-125_13TeV_amcatnlo-pythia8-tauola/Phys14DR-PU40bx25_PHYS14_25_V1-v1/MINIAODSIM

Thanks,
Jan

**Comment by gitytakahas** [comment]
Hi Jan,

Here is the request
https://cmsweb.cern.ch/phedex/prod/Request::View?request=430245

**Comment by mariadalfonso** [comment]
Ciao Yuta.
Can you transfer those samples to the CAF space ?

/SMS-T1bbbb_2J_mGl-1000_mLSP-900_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU40bx25_PHYS14_25_V1-v1/MINIAODSIM
/SMS-T1qqqq_2J_mGl-1000_mLSP-800_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU40bx25_PHYS14_25_V1-v1/MINIAODSIM
/SMS-T1tttt_2J_mGl-1200_mLSP-800_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU40bx25_PHYS14_25_V1-v1/MINIAODSIM
/SMS-T2tt_2J_mStop-425_mLSP-325_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU40bx25_PHYS14_25_V1-v1/MINIAODSIM

/WJetsToLNu_HT-100to200_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM

/QCD_HT_1000ToInf_13TeV-madgraph/Spring14miniaod-141029_PU40bx50_PLS170_V6AN2-v1/MINIAODSIM
/QCD_HT_250To500_13TeV-madgraph/Spring14miniaod-141029_PU40bx50_PLS170_V6AN2-v1/MINIAODSIM
/QCD_HT-500To1000_13TeV-madgraph/Spring14miniaod-PU20bx25_PLS170_V7AN1-v1/MINIAODSIM

/QCD_Pt-300to470_Tune4C_13TeV_pythia8/Spring14miniaod-141029_PU40bx50_castor_PLS170_V6AN2-v1/MINIAODSIM

/SMS-T1bbbb_2J_mGl-1500_mLSP-100_Tune4C_13TeV-madgraph-tauola/Spring14miniaod-141029_PU40bx50_PLS170_V6AN2-v2/MINIAODSIM
/SMS-T1qqqq_2J_mGl-1400_mLSP-100_Tune4C_13TeV-madgraph-tauola/Spring14miniaod-141029_PU40bx50_PLS170_V6AN2-v1/MINIAODSIM
/SMS-T2qq_2J_mStop-1200_mLSP-100_Tune4C_13TeV-madgraph-tauola/Spring14miniaod-141029_PU40bx50_PLS170_V6AN2-v1/MINIAODSIM

/T_tW-channel-DR_Tune4C_13TeV-CSA14-powheg-tauola/Spring14miniaod-141029_PU40bx50_PLS170_V6AN2-v1/MINIAODSIM

/ZJetsToNuNu_HT-600toInf_Tune4C_13TeV-madgraph-tauola/Spring14miniaod-141029_PU40bx50_PLS170_V6AN2-v1/MINIAODSIM

Maria

**Comment by gitytakahas** [comment]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=430790

Yuta

**Comment by gitytakahas** [comment]
Hi Giovanni,

Thanks, I deleted

> /SingleMu/Run2012D-15Apr2014-v1/AOD

https://cmsweb.cern.ch/phedex/prod/Request::View?request=430799

**Comment by gpetruc** [comment]
Happy New Year,

Could you ask the transfer to CAF of this Phys14 MiniAOD:

```
/WJetsToLNu_HT-600toInf_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
```

Thanks,

Giovanni

**Comment by gitytakahas** [comment]
A happy new year,

Here it is,

> https://cmsweb.cern.ch/phedex/prod/Request::View?request=431556

Yuta

**Comment by mariadalfonso** [comment]
Ciao Yuta.
Can you transfer to the CAF space the

/ZJetsToNuNu_HT-400to600_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU20bx25_PHYS14_25_V1-v2/MINIAODSIM

/QCD_HT-100To250_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM

/TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU4bx50_PHYS14_25_V1-v1/MINIAODSIM
/WJetsToLNu_13TeV-madgraph-pythia8-tauola/Phys14DR-PU4bx50_PHYS14_25_V1-v1/MINIAODSIM
/DYJetsToLL_M-50_13TeV-madgraph-pythia8/Phys14DR-PU4bx50_PHYS14_25_V1-v1/MINIAODSIM

Thanks

**Comment by gpetruc** [comment]
Who's working with the very low pileup samples PU4bx50 ?
That said, they might indeed be useful for the startup preparation, if the
run 2 montecarlo will be late.

Ciao,

```
  Giovanni
```

**Comment by mariadalfonso** [comment]
@gpetruc 
I was thinking to use those samples with low PU, to study the effect on the fully hadronic selection (isoTrack veto, lepton veto, met, jetPUID).
I do not think we need all the campain, but those ttbar,W,Z inclusive sample are good for testing.

**Comment by gitytakahas** [comment]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=431674

Yuta

**Comment by degrutto** [comment]
Hi Yuta,

sorry I am rather new ;-)

can you tell me where (i.e. the eos path) physically the samples are transferred? I should have already an account on the cmg t3...
I'd like to check which samples are there already for Hbb....

thanks

   Michele

**Comment by schoef** [comment]
Hello Yuta,

the sample
/WJetsToLNu_HT-600toInf_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
you requested early this week does not seem to be there. Could you maybe
have a look?

Thank you,
Robert

**Comment by gitytakahas** [comment]
Hi Robert,

Yeah, all the requests that I've made during this week has not yet approved by Ian.
Most probably, he is offline. I will ping him (with relevant persons who also have a right to approve the request) but I'm afraid it won't happen during this week. 

Yuta

**Comment by gitytakahas** [comment]
Hi Michele,

Sorry for my late response. I was offline yesterday night. 
You can check it via DAS, just go to following page,

https://cmsweb.cern.ch/das/

and in the blank above, write, for example,

/_/_Phys14*/MINIAODSIM

to show all Phys14 samples. In your case, you might want to use /_BB_/_Phys14_/MINIAODSIM to show H->bb related samples.

Then, click the link, "Files" appeared in each dataset to show actual file location.
If you want to know the sample only sitting at CERN, you can use following query.

> https://cmsweb.cern.ch/das/request?view=list&limit=10&instance=prod%2Fglobal&input=dataset+dataset%3D%2F*BB*%2F*Phys14*%2FMINIAODSIM+site%3DT2_CH_CERN

I hope this helps,
Yuta

**Comment by gitytakahas** [comment]
Hi Robert,

The request has been just approved. 

Yuta

**Comment by mariadalfonso** [comment]
Ciao Yuta.
Can you transfer those PHYS14 samples ?

/QCD_Pt-15to30_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v1/MINIAODSIM
/QCD_Pt-30to50_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v1/MINIAODSIM
/QCD_Pt-50to80_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v2/MINIAODSIM
/QCD_Pt-80to120_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v2/MINIAODSIM
/QCD_Pt-120to170_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v2/MINIAODSIM
/QCD_Pt-300to470_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v2/MINIAODSIM
/QCD_Pt-470to600_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v2/MINIAODSIM
/QCD_Pt-600to800_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v1/MINIAODSIM
/QCD_Pt-800to1000_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v2/MINIAODSIM
/QCD_Pt-1000to1400_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v1/MINIAODSIM
/QCD_Pt-1400to1800_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v1/MINIAODSIM
/QCD_Pt-1800_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_trkalmb_castor_PHYS14_25_V1-v2/MINIAODSIM

**Comment by gitytakahas** [comment]
Hi Maria,

> /DYJetsToLL M-50 13TeV-madgraph-pythia8-tauola v2/Spring14miniaod-141029 PU40bx50 PLS170 V6AN2-v1/MINIAODSIM

Can you check the dataset nama for this and get back to me (there is several blanks) ?

Y.

**Comment by gitytakahas** [comment]
Hi Maria, 

https://cmsweb.cern.ch/phedex/prod/Request::View?request=432050

Y.

**Comment by mariadalfonso** [comment]
Hi Yuta.

Can you transfer this sample  at the CAF ?
/GJets_HT-400to600_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM

Maria

**Comment by gitytakahas** [comment]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=432300

Y.

**Comment by mcitron** [comment]
Hi,

While running CMG (CMGTools-from-CMSSW_7_2_3)  to make ntuples we noticed that the maximum speeds we're getting are around 30-50 events/second. During Run 1 the ntuplising stage usually ran at O1000s events/second. Do you know what could be causing such a slower speed and how it could be optimised? We’ve already exported the complex variable (alphaT) calculation to a C module. 

Best,

Matthew

**Comment by gpetruc** [comment]
Hi Yuta,

Could we also have at CAF `/QCD_Pt-20toInf_MuEnrichedPt15_PionKaonDecay_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_PHYS14_25_V1-v3/MINIAODSIM`

Giovanni

**Comment by gitytakahas** [comment]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=432801

Y.

**Comment by rmanzoni** [comment]
Hi Yuta,

can you transfer this sample?
/WJetsToLNu_13TeV-madgraph-pythia8-tauola/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM                  

thanks,
Riccardo

**Comment by gitytakahas** [comment]
Hi Riccardo,

https://cmsweb.cern.ch/phedex/prod/Request::View?request=433892

Y.

**Comment by cbotta** [comment]
Hi Yuta,

could you transfer these samples:
/QCD_Pt_20to30_bcToE_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_PHYS14_25_V1-v2/MINIAODSIM
/QCD_Pt_30to80_bcToE_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
/QCD_Pt_80to170_bcToE_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_PHYS14_25_V1-v2/MINIAODSIM
/QCD_Pt_170toInf_bcToE_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM

thanks,
cristina

**Comment by gitytakahas** [comment]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=434288

Cheers, Y.

**Comment by cbotta** [comment]
Thanks Yuta,
could you also add:
/QCD_Pt-10to20_EMEnriched_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_castor_PHYS14_25_V1-v1/MINIAODSIM
/QCD_Pt-20to30_EMEnriched_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_castor_PHYS14_25_V1-v2/MINIAODSIM
/QCD_Pt-30to80_EMEnriched_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_castor_PHYS14_25_V1-v1/MINIAODSIM

Cheers,
Cristina

**Comment by pandolf** [comment]
@cbotta is there a reason why you're not requesting 

/QCD_Pt-80to170_EMEnriched_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_castor_PHYS14_25_V1-v1/MINIAODSIM

?

**Comment by gitytakahas** [comment]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=434385

Y.

**Comment by cbotta** [comment]
@pandolf because it is already at T2_CH_CERN

**Comment by cbotta** [comment]
Hi Yuta,

could you please transfer:
QCD_Pt-30to50_MuEnrichedPt5_PionKaonDecay_Tune4C_13TeV_pythia8
QCD_Pt-50to80_MuEnrichedPt5_PionKaonDecay_Tune4C_13TeV_pythia8
QCD_Pt-80to120_MuEnrichedPt5_PionKaonDecay_Tune4C_13TeV_pythia8

thanks
Cristina

**Comment by gitytakahas** [comment]
Hi Cristina,

Could you write down exact Tier structure (e.g, /QCD_Pt-80to170_EMEnriched_Tune4C_13TeV_pythia8/Phys14DR-PU20bx25_castor_PHYS14_25_V1-v1/MINIAODSIM), because with this, I can see several candidates for the samples :

> https://cmsweb.cern.ch/das/request?view=list&limit=10&instance=prod%2Fglobal&input=dataset%3D%2FQCD_Pt-30to50_MuEnrichedPt5_PionKaonDecay_Tune4C_13TeV_pythia8%2F*%2FMINIAODSIM

Cheers, 
Yuta

**Comment by cbotta** [comment]
ups, sorry.

here the complete dataset names:
/QCD_Pt-30to50_MuEnrichedPt5_PionKaonDecay_Tune4C_13TeV_pythia8/Phys14DR-AVE20BX25_tsg_PHYS14_25_V3-v2/MINIAODSIM
/QCD_Pt-50to80_MuEnrichedPt5_PionKaonDecay_Tune4C_13TeV_pythia8/Phys14DR-AVE20BX25_tsg_PHYS14_25_V3-v1/MINIAODSIM
/QCD_Pt-80to120_MuEnrichedPt5_PionKaonDecay_Tune4C_13TeV_pythia8/Phys14DR-AVE20BX25_tsg_PHYS14_25_V3-v1/MINIAODSIM

cristina

**Comment by gitytakahas** [comment]
Here it is : 

https://cmsweb.cern.ch/phedex/prod/Request::View?request=434515

Y.

**Comment by mariadalfonso** [comment]
Ciao Yuta.

Can you transfer again at the CAF the two samples 
SMS-T2bb_2J_mStop-600_mLSP-580_Tune4C_13TeV-madgraph-tauola/PU20bx25_tsg_PHYS14_25_V1-v1/MINIAODSIM
SMS-T2bb_2J_mStop-900_mLSP-100_Tune4C_13TeV-madgraph-tauola/PU20bx25_tsg_PHYS14_25_V1-v1/MINIAODSIM

The files where there for a while but the eos directory are now empty.
 eos ls /eos/cms/store/mc/Phys14DR/SMS-T2bb_2J_mStop-900_mLSP-100_Tune4C_13TeV-madgraph-tauola/MINIAODSIM/PU20bx25_tsg_PHYS14_25_V1-v1/10000
Do you know how it can happen ?

Maria

**Comment by emanueledimarco** [comment]
Hi Yuta, 

can you please ask for the transfer of the following MINIAOD samples (needed for monodies studies):

/DarkMatter_Monojet_M-10_V_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
/DarkMatter_Monojet_M-100_V_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
/DarkMatter_Monojet_M-1000_V_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
/DarkMatter_Monojet_M-1_AV_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
/DarkMatter_Monojet_M-10_AV_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
/DarkMatter_Monojet_M-100_AV_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
/DarkMatter_Monojet_M-1000_AV_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM

thanks a lot,

```
             emanuele
```

**Comment by gitytakahas** [comment]
Hi Emanuele,

You can find the ticket here,

https://cmsweb.cern.ch/phedex/prod/Request::View?request=442308

Following 3 samples were not recognized by phedex (indeed, I could not find these samples in DAS)

> /DarkMatter_Monojet_M-1_AV_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
> /DarkMatter_Monojet_M-100_AV_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM
> /DarkMatter_Monojet_M-1000_AV_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_PHYS14_25_V1-v1/MINIAODSIM

Could you check ?

Best,
Yuta

**Comment by emanueledimarco** [comment]
Hi Yuta, 

thanks a lot. And sorry for those 3 samples. It seems that they have an additional "tsg" in the name... 
They are:

/DarkMatter_Monojet_M-1_AV_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_tsg_PHYS14_25_V1-v1/MINIAODSIM
/DarkMatter_Monojet_M-100_AV_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_tsg_PHYS14_25_V1-v1/MINIAODSIM
/DarkMatter_Monojet_M-1000_AV_Tune4C_13TeV-madgraph/Phys14DR-PU20bx25_tsg_PHYS14_25_V1-v1/MINIAODSIM

Thanks again,
emanuele

**Comment by gitytakahas** [comment]
Sure, here it is,

https://cmsweb.cern.ch/phedex/prod/Request::View?request=442321

Y.
