### ISSUE TITLE
Request sample transfer

### ISSUE THREAD

**Issue by cbotta** [CERN-PH-CMG/cmg-cmssw#17]
Dear Sezen,
I'm starting here a new post that we can use for the requests of new samples to be transferred to produce the PFAOD. I want to test the new version of the production  tools Giovanni just committed (PFAOD, cmgTuple, final-trees with the python framework), so could you please transfer for me the sample:
 /TTWWJets_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/

Thanks,
Cristina

**Comment by cbotta** [comment]
Hello Sezen,
could you please transfer this sample
/SMS-T4tW_Msbottom-325to700_mChargino-150to625_8TeV-Madgraph/Summer12-START52_V9_FSIM/USER 
( it resides in the cms_dbs_ph_analysis_01 database )
thanks a lot

Cristina

**Comment by cbotta** [comment]
Hi Sezen,
could you please request the transfer for these samples? (these ones are - as usual - in the global dbs)
Thanks a lot 
Cristina
/SMS-MadGraph_Pythia6Zstar_8TeV_T1tttt_2J_mGo-400to750_mLSP-1_50GeVX50GeV_Binning/Summer12-START52_V9_FSIM-v1/AODSIM 
/SMS-MadGraph_Pythia6Zstar_8TeV_T1tttt_2J_mGo-800to1400_mLSP-1_50GeVX50GeV_Binning/Summer12-START52_V9_FSIM-v2/AODSIM 
/SMS-MadGraph_Pythia6Zstar_8TeV_T1tttt_2J_mGo-400to750_mLSP-25to550_50GeVX50GeV_Binning/Summer12-START52_V9_FSIM-v1/AODSIM 
/SMS-MadGraph_Pythia6Zstar_8TeV_T1tttt_2J_mGo-775to1075_mLSP-25to500_50GeVX50GeV_Binning/Summer12-START52_V9_FSIM-v3/AODSIM 
/SMS-MadGraph_Pythia6Zstar_8TeV_T1tttt_2J_mGo-775to1075_mLSP-525to875_50GeVX50GeV_Binning/Summer12-START52_V9_FSIM-v3/AODSIM 
/SMS-MadGraph_Pythia6Zstar_8TeV_T1tttt_2J_mGo-1100to1400_mLSP-25to500_50GeVX50GeV_Binning/Summer12-START52_V9_FSIM-v2/AODSIM  
/SMS-MadGraph_Pythia6Zstar_8TeV_T1tttt_2J_mGo-1100to1400_mLSP-525to1000_25GeVX25GeV_Binning/Summer12-START52_V9_FSIM-v2/AODSIM 
/SMS-MadGraph_Pythia6Zstar_8TeV_T1tttt_2J_mGo-1100to1400_mLSP-1025to1200_50GeVX50GeV_Binning/Summer12-START52_V9_FSIM-v1/AODSIM

/SMS-T5VV_2J_mGo-400to750_mLSP-25to525_TuneZ2star_8TeV-madgraph-tauola/Summer12-START53_V7C_FSIM-v1/AODSIM 
/SMS-T5VV_2J_mGo-800to1100_mLSP-25to525_TuneZ2star_8TeV-madgraph-tauola/Summer12-START53_V7C_FSIM-v1/AODSIM 
/SMS-T5VV_2J_mGo-800to1100_mLSP-575to875_TuneZ2star_8TeV-madgraph-tauola/Summer12-START53_V7C_FSIM-v1/AODSIM 
/SMS-T5VV_2J_mGo-1150to1400_mLSP-25to525_TuneZ2star_8TeV-madgraph-tauola/Summer12-START53_V7C_FSIM-v1/AODSIM 
/SMS-T5VV_2J_mGo-1150to1400_mLSP-550to700_TuneZ2star_8TeV-madgraph-tauola/Summer12-START53_V7C_FSIM-v1/AODSIM 
/SMS-T5VV_2J_mGo-1150to1400_mLSP-725to850_TuneZ2star_8TeV-madgraph-tauola/Summer12-START53_V7C_FSIM-v1/AODSIM
/SMS-T5VV_2J_mGo-1150to1400_mLSP-875to1175_TuneZ2star_8TeV-madgraph-tauola/Summer12-START53_V7C_FSIM-v1/AODSIM

**Comment by perrozzi** [comment]
Ciao Sezen,
may I ask to transfer this?
/JPsiToMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/Fall11-PU_S6_START44_V9B-v1/AODSIM

Also, I need to process
/MuOnia/Run2011A-08Nov2011-v1/AOD
/MuOnia/Run2011B-19Nov2011-v1/AOD
what is the procedure to do so?
Apparently they are not hosted at CERN (could you please crosscheck).

Thanks a lot
Luca

**Comment by perrozzi** [comment]
Dear Sezen,
I would like to ask the transfer of the dataset
/JPsiToMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/Fall11-PU_S6_START44_V9B-v1/AODSIM

I also need to process
/MuOnia/Run2011A-08Nov2011-v1/AOD
/MuOnia/Run2011B-19Nov2011-v1/AOD
which apparently are not at CERN, what is the procedure for this?

Thanks a lot in advance

Ciao
Luca

**Comment by ssekmen** [comment]
Hi Luca,
I have sent the request for the MC sample:
https://cmsweb.cern.ch/phedex/prod/Request::View?request=411185

For the data samples, please ask Luca M., since he is the one authorized to make these requests.

cheers,
Sezen
