### ISSUE TITLE
Remove all unneeded multi-object classes

### ISSUE THREAD

**Issue by gpetruc** [CERN-PH-CMG/cmg-cmssw#21]
We have classes and dictionaries for a lot of fancy composite types (e.g. DiMuonDiElectron) many of which are probably unused: which we could clean up to reduce the clutter, save compilation time, library size

Can people tell what they are using? my limited understanding is that ZZ and ttH use none, tau tau probably uses the cmg::DiTau<X,Y> objects, with X,Y being leptons, possibly hadronic susy might use DiObjects with PFJets, BaseJets or Hemispheres.
Does anybody e.g. use the W's (pairs lepton+met) ?

**Comment by steggema** [comment]
Just to confirm that tau-tau has indeed switched to the DiTau objects. In addition, we use the DiMuon  for a few studies, but I guess DiMuon and DiElectron should be kept anyway as they are used in the RootTools examples.

**Comment by gpetruc** [comment]
It's done in 7.0.X since we removed all dataformats
