### ISSUE TITLE
Tag request

### ISSUE THREAD

**Issue by mariadalfonso** [CERN-PH-CMG/cmg-cmssw#256]
Ciao.

This thread will be used by different analyzers to request tags of the code from time to time .

**Comment by mariadalfonso** [comment]
@gpetruc 
Ciao Giovanni.
Can you tag the Heppy + CMGtools, after merging the #255 
This contains the configuration as used by MT2 in the PHYS14 exercises.

Maria for MT2

**Comment by gpetruc** [comment]
Done, the tag is `v7.0.0-from-CMSSW_7_2_3` https://github.com/CERN-PH-CMG/cmg-cmssw/releases/tag/v7.0.0-from-CMSSW_7_2_3
