### ISSUE TITLE
On going production

### ISSUE THREAD

**Issue by cbotta** [CERN-PH-CMG/cmg-cmssw#31]
Hi,

I am going to produce the PFAOD for these samples:

/SMS-T2DegenerateStop_2J_mStop-250to300_mLSP-170to290_TuneZ2star_8TeV-madgraph-tauolapp/Summer12-START53_V19_FSIM_PU_S12-v1/AODSIM
/SMS-T2DegenerateStop_2J_mStop-100to150_mLSP-20to140_TuneZ2star_8TeV-madgraph-tauolapp/Summer12-START53_V19_FSIM_PU_S12-v1/AODSIM
/SMS-T2DegenerateStop_2J_mStop-325to375_mLSP-245to365_TuneZ2star_8TeV-madgraph-tauolapp/Summer12-START53_V19_FSIM_PU_S12-v1/AODSIM
/SMS-T2DegenerateStop_2J_mStop-175to225_mLSP-95to215_TuneZ2star_8TeV-madgraph-tauolapp/Summer12-START53_V19_FSIM_PU_S12-v1/AODSIM

(Please use this thread to tell the others if you are using the cmgtools account to make productions)

Cristina

**Comment by cbotta** [comment]
Hi all,

we are producing the cmgTuple V5_18_0 for the  SUSY signal sample T5VV,

cheers,
Giovanni, Cristina

**Comment by mstoye** [comment]
Hi Chritina,
I made the PFADs for:
/SMS-T2DegenerateStop_2J_mStop-250to300_mLSP-170to290_TuneZ2star_8TeV-madgraph-tauolapp/Summer12-START53_V19_FSIM_PU_S12-v1/AODSIM
/SMS-T2DegenerateStop_2J_mStop-100to150_mLSP-20to140_TuneZ2star_8TeV-madgraph-tauolapp/Summer12-START53_V19_FSIM_PU_S12-v1/AODSIM
/SMS-T2DegenerateStop_2J_mStop-325to375_mLSP-245to365_TuneZ2star_8TeV-madgraph-tauolapp/Summer12-START53_V19_FSIM_PU_S12-v1/AODSIM
/SMS-T2DegenerateStop_2J_mStop-175to225_mLSP-95to215_TuneZ2star_8TeV-madgraph-tauolapp/Summer12-START53_V19_FSIM_PU_S12-v1/AODSIM

Currently I am running the CMGtupels for them

**Comment by cbotta** [comment]
Hi Markus.

ok. on our side we are done with  T1tttt e T5VV samples (we are just resubmitting the failed ones).

cheers,
Cristina

**Comment by mstoye** [comment]
Hi Cristina,
I started a production for the MET datasets.
 /MET/Run2012A-22Jan2013-v1
 /MET/Run2012B-22Jan2013-v1/AOD
 /MET/Run2012C-22Jan2013-v1/AOD
 /METParked/Run2012D-22Jan2013-v1/AOD
Cheers,
Markus

**Comment by cbotta** [comment]
Hi All,
I see only few jobs running on cmgtools, so if no one complain, I am going to send the PAT_CMG_V5_18_0 production for some samples for TTH and SUSY analyses.
(you see the list here: /afs/cern.ch/user/c/cmgtools/work/ProductionSoftware/V5_18_0/cristina/TTH/samples.txt)

cheers,
Cristina

**Comment by gpetruc** [comment]
Hello,

I'm starting now the PFAOD production for these 5 QCD samples so that afterwards they can be deleted from the buffer (submitting as cmgtools from the SL6 node lxplus0062 under screen, using the 8nh queue)

```
/QCD_Pt_20_30_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM
/QCD_Pt_80_170_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM
/QCD_Pt_20_MuEnrichedPt_15_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v3/AODSIM
/QCD_Pt_20_30_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM
/QCD_Pt_30_80_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM
```

Giovanni

**Comment by gpetruc** [comment]
As Luca's processing is done now, I'm starting a small production of the PAT_V5_18_0 of the lepton-enriched QCD samples, that we had only in very old releases. The production is running under screen on lxplus0155 

```
cmgtools%/QCD_Pt_80_170_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/V5_B
cmgtools_group%/QCD_Pt-20to30_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/V5
cmgtools_group%/QCD_Pt-30to50_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/V5
cmgtools_group%/QCD_Pt-50to80_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/V5
cmgtools_group%/QCD_Pt_20_30_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/V5
cmgtools_group%/QCD_Pt_20_30_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/V5
cmgtools_group%/QCD_Pt_20_MuEnrichedPt_15_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v3/AODSIM/V5
cmgtools_group%/QCD_Pt_30_80_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/V5
cmgtools_group%/QCD_Pt_30_80_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/V5_B
cmgtools_group%/QCD_Pt_80_170_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM/V5
```
