### ISSUE TITLE
Phefex Transfer

### ISSUE THREAD

**Issue by mstoye** [CERN-PH-CMG/cmg-cmssw#34]
Hi Sezen,
Could you request the Phedex transfer of:
/MET/Run2012A-22Jan2013-v1/AOD
/MET/Run2012B-22Jan2013-v1/AOD
/MET/Run2012C-22Jan2013-v1/AOD
/METParked/Run2012D-22Jan2013-v1/AOD
Regards,
Markus

**Comment by ssekmen** [comment]
Hi Markus,
These are data samples, so Luca Malgeri is authorized to transfer them.
Can you please ask him?
cheers,
Sezen
