### ISSUE TITLE
Heppy: log.txt file produced by heppy is always empty

### ISSUE THREAD

**Issue by rmanzoni** [CERN-PH-CMG/cmg-cmssw#348]
I came across this problem when I tried to produce some ntuple, using either `splitFactor > 1` or `fineSplitFactor > 1`.
This produces a number of Chunks, but then `heppy_check.py` returns me something like

`[manzoni@lxplus0006 trash]$ heppy_check.py *`
`HiggsTTHInclusive125_Chunk0 cannot find number of processed events`
`...`
`list of bad directories:`
`['HiggsTTHInclusive125_Chunk0',`
`...]`

All the Chunks are bad.

This boils down to the fact that the `log.txt` file which is produced for each Chunk is always empty.

Everything happens in [looper.py](https://github.com/CERN-PH-CMG/cmg-cmssw/blob/CMGTools-from-CMSSW_7_2_3/PhysicsTools/HeppyCore/python/framework/looper.py)
By default, the log messages with severity lower than 'warning' are not written into [`log.txt`](https://github.com/CERN-PH-CMG/cmg-cmssw/blob/CMGTools-from-CMSSW_7_2_3/PhysicsTools/HeppyCore/python/framework/looper.py#L73).
A bunch of messages, including [this](https://github.com/CERN-PH-CMG/cmg-cmssw/blob/CMGTools-from-CMSSW_7_2_3/PhysicsTools/HeppyCore/python/framework/looper.py#L186) for instance, are not saved.

However, `heppy_check.py` [parses](https://github.com/CERN-PH-CMG/cmg-cmssw/blob/CMGTools-from-CMSSW_7_2_3/PhysicsTools/HeppyCore/python/framework/looper.py#L186) `log.txt` and infers the number of processed events from that line. In case it doesn't fint the number of processed events it labels the given Chunk as bad.

This in not the proper behaviour, I believe.
Two possible solutions:
1. stick to the default 'warning' and elevate a number of log messages from info to warning, 
2. lower the severity threshold to 'info'

I went for 2. [in my fork](https://github.com/CERN-PH-CMG/cmg-cmssw/blob/7ca7df9e5cf25663a06415266fb8c8815be07c4f/PhysicsTools/HeppyCore/python/framework/looper.py#L75), but @steggema told me that this was debated in the past and this solution is probably already discarded. 

@gpetruc @cbernet  

EDIT: I am aligned to cgm-central CMGTools-from-CMSSW_7_2_3 branch

**Comment by cbernet** [comment]
Hi Riccardo, 

Thanks for reporting this problem.

The easiest solution is to make sure that the line giving the number of processed events is always written to the log file by using the CRITICAL level only for this line (print with logging.critical), but it’s not too elegant to use such a logging level to ensure that the information is there. 

Alternatively, one could pack some information about the processing in a new, separate file (e.g. json format) written at the end:
number of events processed
time per event
hostname
… 

I prefer the second solution and can implement it next week when I’m back. 

Cheers, 

Colin

PS: this is a sign that we should probably formalize a bit our testing procedures, including checks of the batch tools. 
I will set this up.
