### ISSUE TITLE
Wigner's effect

### ISSUE THREAD

**Issue by perrozzi** [CERN-PH-CMG/cmg-cmssw#38]
Dear all, while moving most of the cpu to lxplus6, CERN has extended the computing centre with capacity installed at the Wigner Data Centre in Budapest [*], and the new resources are added transparently for the users, so jobs can go to Hungary.
There is a known CPU efficiency issue for I/O intensive jobs running at Wigner and reading data from EOS in Meyrin.
I am not aware of ways to avoid this with bsub command specifications.

The complete thread can be found here
https://savannah.cern.ch/support/?142241#comment13

Ciao
Luca

[*]This will affect only SLC6 jobs, because there are no SLC5 worker nodes in Wigner

**Comment by adavidzh** [comment]
Wigner seems to have specific host groups:

``` bash
$ bmgroup -w | grep wig | cut -d ' ' -f 1
g_wigner
g_sharewigner
```

Only `g_sharewigner` is part of the public queues. So, for instance, to try and avoid this host group in the `test` queues, you can try:

``` bash
$ bqueues -l test | grep HOST
HOSTS:  g_sharelong/ g_aishare/ lxbsq1535 g_sharewigner/ g_shareshared/
$ bsub -q test -m "g_sharelong g_shareshared g_aishare" "uname -a"
Job <515903063> is submitted to queue <test>.
$ grep Linux LSFJOB_515903063/STDOUT
Linux bg6dc92d53e 2.6.32-358.23.2.el6.x86_64 #1 SMP Thu Oct 17 10:27:22 CEST 2013 x86_64 x86_64 x86_64 GNU/Linux
 under linux version Scientific Linux CERN SLC release 6.5 (Carbon)
$ bmgroup -w | grep bg6dc92d53e | cut -d ' ' -f1
g_g_aishare
g_amd
g_wan
g_exe
g_share
g_cvmfs
g_lcg
g_aishare
```

So the host where it ran was indeed not in `g_sharewigner`.

Hope this helps dodging dodgy hosts in general.

ps - `bsub -m` also allows to set preferences among host groups.

**Comment by gpetruc** [comment]
Apparently submitting with

```
pybatch [...]  -b 'bsub -q 8nh -oo stdout.txt -m "g_aishare g_atlascaturgent g_share g_sharelong g_shareshared lxbsq1535" -J Prod < batchScript.sh'
```

is NOT enough since some nodes are in multiple shares: e.g. I ended up in b696b16ea7 which is in g_aishare but also in g_sharewigner.

Talking to Josh, they have similar problems in the generator group and they didn't yet found a simple workaround.

**Comment by perrozzi** [comment]
I also had (a lot of) problems with emails and I just put them down with
-u pippo123
(if there is such a username at cern, the person will probably complain
soon or later :-) )

**Comment by adavidzh** [comment]
If one day the `8nh` definition changes, then

``` bash
bqueues -l 8nh | grep HOSTS | cut -d':' -f2- | tr -d '/' | tr ' ' '\n' | grep -v wigner | tr '\n' ' '
```

still works.
