### ISSUE TITLE
Store only the sign of gen weights, normalize PDF weights, add scale variation weights

### ISSUE THREAD

**Issue by perrozzi** [CERN-PH-CMG/cmg-cmssw#444]
Ciao,
I think that it would make sense to store only the sign of the gen weight
instead of its absolute value
https://github.com/CERN-PH-CMG/cmg-cmssw/blob/CMGTools-from-CMSSW_7_4_7/PhysicsTools/Heppy/python/analyzers/core/AutoFillTreeProducer.py#L127
since only the former is a meaningful quantity, see for instance
https://hypernews.cern.ch/HyperNews/CMS/get/generators/2679/1.html

Also the PDF weights could be normalized to the absolute value of the gen weight.

Finally, are the scale variation weights stored? They could also be useful, I am not sure I found them but maybe they are somewhere else.

What do you think?

**Comment by gpetruc** [comment]
Hi Luca,

For some generators or filters (the multi-hadronizer ones) also the value
of the weight is important.

Giovanni
Il 16-lug-2015 03:08, "perrozzi" notifications@github.com ha scritto:

**Comment by perrozzi** [comment]
ok thanks, I see.
What about scale uncertainties? Are they currently stored?
