### ISSUE TITLE
Transfer Request @ RunIISpring15DR74 campaign

### ISSUE THREAD

**Issue by safarzad** [CERN-PH-CMG/cmg-cmssw#503]
Hi Yuta,

Could you transfer this sample. 
Thanks

/ZJetsToNuNu_HT-100To200_13TeV-madgraph/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/MINIAODSIM

**Comment by gitytakahas** [comment]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=473983

Y.

2015-09-02 10:10 GMT+03:00 safarzad notifications@github.com:

> Hi Yuta,
> 
> Could you transfer this sample.
> Thanks
> 
> /ZJetsToNuNu_HT-100To200_13TeV-madgraph/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/MINIAODSIM
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503.

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by bachtis** [comment]
Hi Yuta , I need a sample for POG studies in AOD.Can we get in please?
 /QCD_Pt-15TTo7000_TuneZ2star-Flat_13TeV_pythia6/RunIISpring15DR74-Asympt50ns_MCRUN2_74_V9A-v1/AODSIM

**Comment by gitytakahas** [comment]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=478288

Y.

2015-09-14 13:33 GMT+02:00 Michalis Bachtis notifications@github.com:

> Hi Yuta , I need a sample for POG studies in AOD.Can we get in please?
> 
> /QCD_Pt-15TTo7000_TuneZ2star-Flat_13TeV_pythia6/RunIISpring15DR74-Asympt50ns_MCRUN2_74_V9A-v1/AODSIM
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503#issuecomment-140045419
> .

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by cbernet** [comment]
Hi Yuta, 

Could you please transfer the following sample for the PF paper studies? 

/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/MINIAODSIM

Thanks, 

Colin

**Comment by gitytakahas** [comment]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=478321

Y.

2015-09-14 16:17 GMT+02:00 Colin Bernet notifications@github.com:

> Hi Yuta,
> 
> Could you please transfer the following sample for the PF paper studies?
> 
> /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/MINIAODSIM
> 
> Thanks,
> 
> Colin
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503#issuecomment-140092866
> .

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by cbernet** [comment]
Hi Yuta, could you please transfer the following two datasets for PF paper MET studies? 

/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO

 /TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-AsymptNoPU_MCRUN2_74_V9A-v2/AODSIM

Unfortunately there is no AODSIM for the first sample,
and we cannot use MINIAODSIM for these studies.

Cheers, 

Colin

**Comment by gitytakahas** [comment]
Hi Colin,

https://cmsweb.cern.ch/phedex/prod/Request::View?request=540363

Since this is rather large file and now occupied our local buffer, please
let me know if there is any samples that can be deleted (especially the one
used for past PF studies ?)

Thanks !
Yuta

2015-12-07 13:06 GMT+01:00 Colin Bernet notifications@github.com:

> Hi Yuta, could you please transfer the following two datasets for PF paper
> MET studies?
> 
> /QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO
> 
> /TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-AsymptNoPU_MCRUN2_74_V9A-v2/AODSIM
> 
> Unfortunately there is no AODSIM for the first sample,
> and we cannot use MINIAODSIM for these studies.
> 
> Cheers,
> 
> Colin
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503#issuecomment-162506071
> .

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by cbernet** [comment]
Hi Yuta, 

Thanks! 

Could you please let me know the name and the size of the samples I have requested that are still in the buffer? 

Also, do you know how to subscribe to only part of the datasets I’ve just requested, as once suggested by Giovanni? 
I guess that 1 million events would be enough in both cases.

Cheers, 

Colin

**Comment by gitytakahas** [comment]
Hi Colin,

Could you please let me know the name and the size of the samples I have

> requested that are still in the buffer?

I think followings are the one (You check check them at phedex page(*)

/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO
/QCD_Pt-15TTo7000_TuneZ2star-Flat_13TeV_pythia6/RunIISpring15DR74-Asympt50ns_MCRUN2_74_V9A-v1/AODSIM
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RAW
/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RAW
/QCD_Pt-80to120_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISpring15DR74-AsymptNoPUReco_MCRUN2_74_V9A-v1/GEN-SIM-RECO
/QCD_Pt-120to170_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISpring15DR74-AsymptNoPUReco_MCRUN2_74_V9A-v1/GEN-SIM-RECO

> Also, do you know how to subscribe to only part of the datasets I’ve just
> requested, as once suggested by Giovanni?
> I guess that 1 million events would be enough in both cases.

You can request the blocks. To request a block instead of the full sample,
just put the path including the path and the hash in the phedex request.
something like, A/B/C#BLOCK.
You can find the list of blocks at,

https://cmsweb.cern.ch/das/request?input=block%20dataset%3D/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO&instance=prod/global&idx=0&limit=10

Cheers,
Yuta

(*)
https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1344868584%3Bgroup%3Dlocal%3Bnode%3D1561

> Cheers,
> 
> Colin
> 
> Le 7 déc. 2015 à 13:12, Yuta Takahashi notifications@github.com a écrit
> :
> 
> > Hi Colin,
> > 
> > https://cmsweb.cern.ch/phedex/prod/Request::View?request=540363
> > 
> > Since this is rather large file and now occupied our local buffer, please
> > let me know if there is any samples that can be deleted (especially the
> > one
> > used for past PF studies ?)
> > 
> > Thanks !
> > Yuta
> > 
> > 2015-12-07 13:06 GMT+01:00 Colin Bernet notifications@github.com:
> > 
> > > Hi Yuta, could you please transfer the following two datasets for PF
> > > paper
> > > MET studies?
> > > 
> > > /QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO
> > > 
> > > /TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-AsymptNoPU_MCRUN2_74_V9A-v2/AODSIM
> > > 
> > > Unfortunately there is no AODSIM for the first sample,
> > > and we cannot use MINIAODSIM for these studies.
> > > 
> > > Cheers,
> > > 
> > > Colin
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503#issuecomment-162506071
> > > 
> > > .
> > 
> > ## 
> > 
> > Yuta Takahashi
> > LHC - CMS experiment,
> > CERN (European Organization for Nuclear Research)
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503#issuecomment-162510169
> .

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by milosdjordjevic** [comment]
Hi Yuta,

Could you please keep this sample (used recently for the PF paper):

/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RAW

since I need it still for the PF studies the HLT (transition to L2PFJets).

For this I would also need the RECO sample (Colin already requested):

/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO 

Thanks,
Milos

**Comment by cbernet** [comment]
Hi again, Yuta, please have a look inline. 

Le 7 déc. 2015 à 14:17, Yuta Takahashi notifications@github.com a écrit :

> Hi Colin,
> 
> Could you please let me know the name and the size of the samples I have
> 
> > requested that are still in the buffer?
> 
> I think followings are the one (You check check them at phedex page(*)
> 
> /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO

I don’t think the following sample belongs to us: 

> /QCD_Pt-15TTo7000_TuneZ2star-Flat_13TeV_pythia6/RunIISpring15DR74-Asympt50ns_MCRUN2_74_V9A-v1/AODSIM
> 
> /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RAW
> /QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RAW
> /QCD_Pt-80to120_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISpring15DR74-AsymptNoPUReco_MCRUN2_74_V9A-v1/GEN-SIM-RECO
> /QCD_Pt-120to170_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISpring15DR74-AsymptNoPUReco_MCRUN2_74_V9A-v1/GEN-SIM-RECO

you may delete all AsymptNoPU samples listed above 
provided you get the green light from Cristina. 
I think she’s been using them as well. 

> > Also, do you know how to subscribe to only part of the datasets I’ve just
> > requested, as once suggested by Giovanni?
> > I guess that 1 million events would be enough in both cases.
> 
> You can request the blocks. To request a block instead of the full sample,
> just put the path including the path and the hash in the phedex request.
> something like, A/B/C#BLOCK.
> You can find the list of blocks at,
> 
> https://cmsweb.cern.ch/das/request?input=block%20dataset%3D/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO&instance=prod/global&idx=0&limit=10

Thanks! 
So can you cancel the tranfer of the whole QCD sample to instead request the following blocks? 

/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO#03aa7784-1505-11e5-a247-001e67abf518
/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO#03adb124-1505-11e5-a247-001e67abf518
/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO#05cb984c-1508-11e5-9f48-a0369f23cf8a
/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO#19d03b0e-1503-11e5-9f48-a0369f23cf8a

For TTJets I would still like to get the full sample, if possible. 

Cheers, 

Colin

**Comment by gitytakahas** [comment]
Hi Colin,

> /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RAW
> 
> > /QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RAW
> > 
> > /QCD_Pt-80to120_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISpring15DR74-AsymptNoPUReco_MCRUN2_74_V9A-v1/GEN-SIM-RECO
> > 
> > /QCD_Pt-120to170_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISpring15DR74-AsymptNoPUReco_MCRUN2_74_V9A-v1/GEN-SIM-RECO
> 
> you may delete all AsymptNoPU samples listed above
> provided you get the green light from Cristina.
> I think she’s been using them as well.

OK. I will wait Cristina's reply then.

> > > Also, do you know how to subscribe to only part of the datasets I’ve
> > > just
> > > requested, as once suggested by Giovanni?
> > > I guess that 1 million events would be enough in both cases.
> > 
> > You can request the blocks. To request a block instead of the full
> > sample,
> > just put the path including the path and the hash in the phedex request.
> > something like, A/B/C#BLOCK.
> > You can find the list of blocks at,
> > 
> > https://cmsweb.cern.ch/das/request?input=block%20dataset%3D/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO&instance=prod/global&idx=0&limit=10
> 
> Thanks!
> So can you cancel the tranfer of the whole QCD sample to instead request
> the following blocks?
> 
> /QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO#03aa7784-1505-11e5-a247-001e67abf518
> 
> /QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO#03adb124-1505-11e5-a247-001e67abf518
> 
> /QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO#05cb984c-1508-11e5-9f48-a0369f23cf8a
> 
> /QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO#19d03b0e-1503-11e5-9f48-a0369f23cf8a

For TTJets I would still like to get the full sample, if possible.


Thanks, I just submitted the new request
https://cmsweb.cern.ch/phedex/prod/Request::View?request=540380
https://cmsweb.cern.ch/phedex/prod/Request::View?request=540381

> /QCD_Pt-15TTo7000_TuneZ2star-Flat_13TeV_pythia6/RunIISpring15DR74-Asympt50ns_MCRUN2_74_V9A-v1/AODSIM

does anybody using this ? If not, I will request deletion tomorrow.

Thanks,
Yuta

> Cheers,
> 
> Colin
> 
> > Cheers,
> > Yuta
> > 
> > (*)
> > 
> > https://cmsweb.cern.ch/phedex/prod/Data::Subscriptions#state=create_since%3D1344868584%3Bgroup%3Dlocal%3Bnode%3D1561
> > 
> > > Cheers,
> > > 
> > > Colin
> > > 
> > > Le 7 déc. 2015 à 13:12, Yuta Takahashi notifications@github.com a
> > > écrit
> > > :
> > > 
> > > > Hi Colin,
> > > > 
> > > > https://cmsweb.cern.ch/phedex/prod/Request::View?request=540363
> > > > 
> > > > Since this is rather large file and now occupied our local buffer,
> > > > please
> > > > let me know if there is any samples that can be deleted (especially
> > > > the
> > > > one
> > > > used for past PF studies ?)
> > > > 
> > > > Thanks !
> > > > Yuta
> > > > 
> > > > 2015-12-07 13:06 GMT+01:00 Colin Bernet notifications@github.com:
> > > > 
> > > > > Hi Yuta, could you please transfer the following two datasets for
> > > > > PF
> > > > > paper
> > > > > MET studies?
> > > 
> > > /QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO
> > > 
> > > 
> > > /TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-AsymptNoPU_MCRUN2_74_V9A-v2/AODSIM
> > > 
> > > > > Unfortunately there is no AODSIM for the first sample,
> > > > > and we cannot use MINIAODSIM for these studies.
> > > > > 
> > > > > Cheers,
> > > > > 
> > > > > Colin
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > 
> > > https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503#issuecomment-162506071
> > > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Yuta Takahashi
> > > > LHC - CMS experiment,
> > > > CERN (European Organization for Nuclear Research)
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503#issuecomment-162510169
> > > 
> > > .
> > 
> > ## 
> > 
> > Yuta Takahashi
> > LHC - CMS experiment,
> > CERN (European Organization for Nuclear Research)
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503#issuecomment-162527268
> .

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by steggema** [comment]
Hi Yuta,

Can you transfer the following AODSIM files?

/SUSYGluGluToHToTauTau_M-500_TuneCUETP8M1_13TeV-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
/SUSYGluGluToBBHToTauTau_M-500_TuneCUETP8M1_13TeV-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
/GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM

These won't be needed for more than 2 weeks. 
Thanks,
Jan

**Comment by gitytakahas** [comment]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=591056

Y.

2016-01-28 11:07 GMT+01:00 Jan Steggemann notifications@github.com:

> Hi Yuta,
> 
> Can you transfer the following AODSIM files?
> 
> /SUSYGluGluToHToTauTau_M-500_TuneCUETP8M1_13TeV-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> 
> /SUSYGluGluToBBHToTauTau_M-500_TuneCUETP8M1_13TeV-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> 
> /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> 
> /GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> 
> These won't be needed for more than 2 weeks.
> Thanks,
> Jan
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503#issuecomment-176100940
> .

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by gitytakahas** [comment]
Hi all,

Our buffer is being occupied now again.
I would propose to delete following gigantic DYJet samples, if nobody is
using now.
Please let me know a.s.a.p if somebody is still using this.

/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RAW
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO

If I don't get any reply during today, I will ask for the deletion.

Thanks,
Yuta

2016-01-28 11:10 GMT+01:00 Yuta Takahashi Yuta.Takahashi@cern.ch:

> https://cmsweb.cern.ch/phedex/prod/Request::View?request=591056
> 
> Y.
> 
> 2016-01-28 11:07 GMT+01:00 Jan Steggemann notifications@github.com:
> 
> > Hi Yuta,
> > 
> > Can you transfer the following AODSIM files?
> > 
> > /SUSYGluGluToHToTauTau_M-500_TuneCUETP8M1_13TeV-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> > 
> > /SUSYGluGluToBBHToTauTau_M-500_TuneCUETP8M1_13TeV-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> > 
> > /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> > 
> > /GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> > 
> > These won't be needed for more than 2 weeks.
> > Thanks,
> > Jan
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503#issuecomment-176100940
> > .
> 
> ## 
> 
> Yuta Takahashi
> LHC - CMS experiment,
> CERN (European Organization for Nuclear Research)

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by gitytakahas** [comment]
Since I didn't receive anything, I requested the removal of DYJets sample
from buffer.

https://cmsweb.cern.ch/phedex/prod/Request::View?request=591748

Yuta

2016-01-28 11:18 GMT+01:00 Yuta Takahashi Yuta.Takahashi@cern.ch:

> Hi all,
> 
> Our buffer is being occupied now again.
> I would propose to delete following gigantic DYJet samples, if nobody is
> using now.
> Please let me know a.s.a.p if somebody is still using this.
> 
> /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RAW
> 
> /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-AsymptNoPURawReco_MCRUN2_74_V9A-v4/GEN-SIM-RECO
> 
> If I don't get any reply during today, I will ask for the deletion.
> 
> Thanks,
> Yuta
> 
> 2016-01-28 11:10 GMT+01:00 Yuta Takahashi Yuta.Takahashi@cern.ch:
> 
> > https://cmsweb.cern.ch/phedex/prod/Request::View?request=591056
> > 
> > Y.
> > 
> > 2016-01-28 11:07 GMT+01:00 Jan Steggemann notifications@github.com:
> > 
> > > Hi Yuta,
> > > 
> > > Can you transfer the following AODSIM files?
> > > 
> > > /SUSYGluGluToHToTauTau_M-500_TuneCUETP8M1_13TeV-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> > > 
> > > /SUSYGluGluToBBHToTauTau_M-500_TuneCUETP8M1_13TeV-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> > > 
> > > /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> > > 
> > > /GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
> > > 
> > > These won't be needed for more than 2 weeks.
> > > Thanks,
> > > Jan
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/CERN-PH-CMG/cmg-cmssw/issues/503#issuecomment-176100940
> > > .
> > 
> > ## 
> > 
> > Yuta Takahashi
> > LHC - CMS experiment,
> > CERN (European Organization for Nuclear Research)
> 
> ## 
> 
> Yuta Takahashi
> LHC - CMS experiment,
> CERN (European Organization for Nuclear Research)

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)
