### ISSUE TITLE
Transfer flat QCD no pileup sample

### ISSUE THREAD

**Issue by cbernet** [CERN-PH-CMG/cmg-cmssw#504]
Hi Yuta, 

Could you please transfer this sample for the PF paper studies? 

/QCD_Pt-15to20_EMEnriched_TuneCUETP8M1_13TeV_pythia8/RunIISpring15DR74-AsymptNoPUReco_MCRUN2_74_V9A-v1/GEN-SIM-RECO

Many thanks, 

Colin

**Comment by cbernet** [comment]
@cbotta @gitytakahas

**Comment by gitytakahas** [comment]
I submitted a ticket for the local buffer.

https://cmsweb.cern.ch/phedex/prod/Request::View?request=475510

Yuta

2015-09-07 13:22 GMT+02:00 Colin Bernet notifications@github.com:

> @cbotta https://github.com/cbotta @gitytakahas
> https://github.com/gitytakahas
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/504#issuecomment-138274111
> .

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)
