### ISSUE TITLE
  Transfer Request @ RunIISpring15DR74 campaign

### ISSUE THREAD

**Issue by safarzad** [CERN-PH-CMG/cmg-cmssw#511]
Could you please transfer this sample:

/SMS-T1bbbb_mGluino-1500_mLSP-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/MINIAODSIM

Thanks,
Batool

**Comment by gitytakahas** [comment]
Hi Batool,

https://cmsweb.cern.ch/phedex/prod/Request::View?request=478604

From next time, please submit your request at,

https://github.com/CERN-PH-CMG/cmg-cmssw/issues/376

Best,
Yuta

2015-09-15 14:56 GMT+02:00 safarzad notifications@github.com:

> Could you please transfer this sample:
> 
> /SMS-T1bbbb_mGluino-1500_mLSP-100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/MINIAODSIM
> 
> Thanks,
> Batool
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CERN-PH-CMG/cmg-cmssw/issues/511.

## 

Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)
