### ISSUE TITLE
70X: Lepton IDs

### ISSUE THREAD

**Issue by gpetruc** [CERN-PH-CMG/cmg-cmssw#63]
Somebody should take care that any development on lepton IDs in 7.0.X is propagated to the CMGTools python classes.

Currently, what's implemented is:
- For muons, we get the same IDs as Run 1 plus whatever is provided by the "muonID" method of pat::Muon (e.g. the RPC muon IDs)
- For electrons, we have the Run 1 MVA IDs using the Run 1 training and the 7.0.X shower shapes. 

As a sensible starting point for CSA14 we probably want at least to have at least also the Run 1 Cut-based, and to have for both IDs the choice between 7.0.X shower shapes and 5.3.X shower shapes (the "full5x5" ones)

**Comment by emanueledimarco** [comment]
> For electrons, we have the Run 1 MVA IDs using the Run 1 training and the 7.0.X shower shapes.

If the shower shapes are the ones of 7.0.0 the Run1 ID is not bad. There is a HZZ4e sample that we asked in 7.0.0 to the PPD to redo the training that should arrive within days and then redoing a reasonable training should be very easy (and it should be only matter of changing the weights file if we leave the same set of variables)

**Comment by gpetruc** [comment]
Ciao,

I've made a quick comparison of the different electron ID things (on ttbar 25ns MC), you can see the two plots below.
Basically:
- for the cut-based ID, the new CSA14 working points using the full5x5 shower shapes work better than the old 2012 working points both with new and old shapes
- the 2012 MVA training works better with the full5x5 shower shape (no surprise since the training was done on those)
- the performance of the loose MVA WP is not much different from 5.3.X: eff(s) = 98%, eff(b) = 26% (was eff(s) = 98.5% for eff(b) = 24%)

So, to have a reasonable startig point for now I'd leave in the old MVA with full5x5 and the CSA14 cut-based (to avoid saving 100 different ids in the trees), and stay with the same loose lepton id definition that we had in the past. Then when we have a new MVA training from Emanuele we switch to that.

![eleids_2014_zoom](https://cloud.githubusercontent.com/assets/4643655/3525714/b7d55452-0775-11e4-935d-f35c993c46e9.png)
![eleids_2014](https://cloud.githubusercontent.com/assets/4643655/3525715/b800ea86-0775-11e4-8be0-1820a1c1c059.png)

**Comment by gpetruc** [comment]
A new training of the Electron ID exists for the CSA14 25ns and 50ns scenarios.
https://twiki.cern.ch/twiki/bin/viewauth/CMS/MultivariateElectronIdentificationRun2
Can somebody update the xml files we're using, and check that the new works better than the old.
I'd leave in both the 25ns and 50ns trainings, but use the 50ns as default since anyway only the 50ns scenario is really useful for physics on the CSA14 samples with no OOT pileup rejection.

**Comment by emanueledimarco** [comment]
Hi Giovanni, 

I can have a look at this. But consider that this is likely to change (by a lot) if the changes of the reconstruction in ECAL and tracker that are in 720 will stay for Run 2. At that point I think that the Run1 training would be a better approximation than the CSA14 training (that is biased by a lot of oot pu). Anyway we will not discover this before we have some samples of the Phys14, which means November I guess...

```
     Emanuele
```
