### ISSUE TITLE
Transfer Request @ RunIISpring16MiniAODv1+2 campaign (80X)

### ISSUE THREAD

**Issue by peruzzim** [CERN-PH-CMG/cmg-cmssw#658]
Hi @mdunser,

 can you please transfer the following datasets?

/QCD_Pt-30to50_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
/QCD_Pt-170to300_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

**Comment by mdunser** [comment]
Hi Marco,
see here: https://cmsweb.cern.ch/phedex/prod/Request::View?request=701219
-m

On 17 Jun 2016, at 13:58, peruzzim <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @mdunserhttps://github.com/mdunser,

can you please transfer the following datasets?

/QCD_Pt-30to50_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
/QCD_Pt-170to300_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

**Comment by steggema** [comment]
Hi Marc,

Can you please transfer the following datasets:

/ZZTo4L_13TeV_powheg_pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/VBFHToTauTau_M125_13TeV_powheg_pythia8/RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

Thanks,
Jan

**Comment by mdunser** [comment]
Hi Jan,

here you go: https://cmsweb.cern.ch/phedex/prod/Request::View?request=713692

-m

On 29 Jun 2016, at 10:44, Jan Steggemann <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

Can you please transfer the following datasets:

/ZZTo4L_13TeV_powheg_pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/VBFHToTauTau_M125_13TeV_powheg_pythia8/RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

Thanks,
Jan

**Comment by safarzad** [comment]
Hi,

Could you please transfer this dataset:
/WW_TuneCUETP8M1_13TeV-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

**Comment by mdunser** [comment]
Hi,
request is made: https://cmsweb.cern.ch/phedex/prod/Request::View?request=731570
-m

On 07 Jul 2016, at 16:05, safarzad <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

Could you please transfer this dataset:
/WW_TuneCUETP8M1_13TeV-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

**Comment by safarzad** [comment]
Hi,

Thanks, could you transfer this sample too:

/TTJets_DiLept_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0_ext1-v1/MINIAODSIM  

Best,
Batool

**Comment by mdunser** [comment]
Hi Batool,
request is made: https://cmsweb.cern.ch/phedex/prod/Request::View?request=732803
-m

On 10 Jul 2016, at 12:26, safarzad <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

Thanks, could you transfer this sample too:

/TTJets_DiLept_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0_ext1-v1/MINIAODSIM

Best,
Batool

**Comment by clelange** [comment]
Hi Marc,

Could you please request the following samples:

```
/QCD_HT*to*_BGenFilter_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/*MiniAODv2*/MINIAODSIM
/QCD_bEnriched*HT*to*_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/*MiniAODv2*/MINIAODSIM
```

These are 76X and 80X samples (16 each, but one 76X is not yet completely done). If it makes book-keeping easier, I can also request the 76X ones in the other issue.

Thank you,
Clemens

**Comment by mdunser** [comment]
Hi Clemens,

could you either post all actual dataset names or at least some string that I can simply type into DAS to get
the correct list?
It’s a huge pain (and error prone) to try and look up the correct datasets, especially if it’s 32 of them.

The actual github issue where you post it makes no real difference, so that’s fine.

Thanks,
-m

On 13 Jul 2016, at 11:13, Clemens Lange <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

Could you please request the following samples:
/QCD_HTto_BGenFilter_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/MiniAODv2/MINIAODSIM
/QCD_bEnrichedHTto_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/MiniAODv2*/MINIAODSIM

These are 76X and 80X samples (16 each, but one 76X is not yet completely done). If it makes book-keeping easier, I can also request the 76X ones in the other issue.

Thank you,
Clemens

**Comment by clelange** [comment]
OK, I hadn't seen that the markdown formatting had messed up the wildcards, I updated the comment above so that you can just paste the two lines.

**Comment by mdunser** [comment]
Hi,

request is made: https://cmsweb.cern.ch/phedex/prod/Request::View?request=736375

it's 31 samples. As long as the last sample isn’t complete, it’s not included in the request.

Have a good wednesday,
-m

On 13 Jul 2016, at 11:45, Clemens Lange <notifications@github.com<mailto:notifications@github.com>> wrote:

OK, I hadn't seen that the markdown formatting had messed up the wildcards, I updated the comment above so that you can just paste the two lines.

**Comment by mariadalfonso** [comment]
HI Marc.
Can you transfer these samples ?

/TTGJets_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/GJets_HT-600ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

**Comment by mdunser** [comment]
Hi Maria,

here you go: https://cmsweb.cern.ch/phedex/prod/Request::View?request=737830

-m

On 15 Jul 2016, at 11:48, mariadalfonso <notifications@github.com<mailto:notifications@github.com>> wrote:

HI Marc.
Can you transfer these samples ?

/TTGJets_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/GJets_HT-600ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

**Comment by peruzzim** [comment]
Hi Marc, can you please urgently transfer this? Thanks.

/ttHJetToNonbb_M125_13TeV_amcatnloFXFX_madspin_pythia8_mWCutfix/RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_reHLT_80X_mcRun2_asymptotic_v14_ext1-v1/MINIAODSIM

**Comment by mdunser** [comment]
Hi Marco,

request is made here: https://cmsweb.cern.ch/phedex/prod/Request::View?request=738583

enjoy the weekend,
-m

On 16 Jul 2016, at 12:03, peruzzim <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc, can you please urgently transfer this? Thanks.

/ttHJetToNonbb_M125_13TeV_amcatnloFXFX_madspin_pythia8_mWCutfix/RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_reHLT_80X_mcRun2_asymptotic_v14_ext1-v1/MINIAODSIM

**Comment by steggema** [comment]
Hi Marc, all,

This is maybe not the right thread, but I just realised that e.g. the SingleMuon 2016B and 2016C MINIAOD datasets are not anymore at CERN (*). Can we get them back?

Thanks,
Jan

(*)
https://cmsweb.cern.ch/das/request?view=list&instance=prod%2Fglobal&input=site+dataset%3D%2FSingleMuon%2FRun2016B-PromptReco-v2%2FMINIAOD
https://cmsweb.cern.ch/das/request?view=list&instance=prod%2Fglobal&input=site+dataset%3D%2FSingleMuon%2FRun2016C-PromptReco-v2%2FMINIAOD

**Comment by mdunser** [comment]
Hi Jan,

this is as good a forum as any. I also realized yesterday that almost none of the RunC datasets are subscribed to the local space. After talking to some people (and from what I remember) there _should_ be an agreement that at least all the MINIAODs are subscribed to CERN, but quite clearly this is not the case.

For now, I will collect relevant RunB, C and D datasets and request them to be transferred to the local space in order to perhaps have them ready for any last ICHEP rush.

I will also talk to CompOps and try to get open subscriptions again for anything post-ICHEP (i.e. starting from RunE).

Which datasets are needed/wanted from the different analyzers? I'll for sure request double-leptonic PDs and the SingleMuon, but am open to suggestions for more stuff. 

Best,
-m

**Comment by steggema** [comment]
Hi Marc,

> On 22 Jul 2016, at 11:51, mdunser notifications@github.com wrote:
> 
> Hi Jan,
> 
> this is as good a forum as any. I also realized yesterday that almost none of the RunC datasets are subscribed to the local space. After talking to some people (and from what I remember) there should be an agreement that at least all the MINIAODs are subscribed to CERN, but quite clearly this is not the case.
> 
> For now, I will collect relevant RunB, C and D datasets and request them to be transferred to the local space in order to perhaps have them ready for any last ICHEP rush.
> 
> I will also talk to CompOps and try to get open subscriptions again for anything post-ICHEP (i.e. starting from RunE).
> 
> Which datasets are needed/wanted from the different analyzers? I'll for sure request double-leptonic PDs and the SingleMuon, but am open to suggestions for more stuff.

We'll also need the Tau datasets (still at CERN though so no action necessary at the moment), and at some point the SingleElectron ones, but this isn't urgent.

Thanks,
Jan

**Comment by mariadalfonso** [comment]
Hi Marc.

did you already asked for the re-transfer of these ? 
DoubleMuon_Run2016C_PromptReco_v2
DoubleEG_Run2016B_PromptReco_v2
DoubleEG_Run2016C_PromptReco_v2
If not please transfer then asap.

Thanks

**Comment by mdunser** [comment]
Ciao Maria,

I had made that request straight away. However it is still pending approval
https://cmsweb.cern.ch/phedex/prod/Request::View?request=742722

In the meantime, there is always the option of useAAA, which at least for our
analysis has worked nicely these last weeks.

Have a good sunday,
-m

On 24 Jul 2016, at 10:53, mariadalfonso <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc.

did you already asked for the re-transfer of these ?
DoubleMuon_Run2016C_PromptReco_v2
DoubleEG_Run2016B_PromptReco_v2
DoubleEG_Run2016C_PromptReco_v2
If not please transfer then asap.

Thanks

**Comment by steggema** [comment]
Hi Marc,

Can you also transfer /Tau/Run2016D-PromptReco-v2/MINIAOD?

Thanks again,
Jan

PS: Looks like we should add another thread if these keep getting deleted very soon after completion...

https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=site+dataset%3D%2FTau%2FRun2016D-PromptReco-v2%2FMINIAOD

**Comment by mdunser** [comment]
Hi Jan,

request is made: https://cmsweb.cern.ch/phedex/prod/Request::View?request=745536

I’m following up with compops and others to investigate why this is happening.
-m

On 25 Jul 2016, at 11:09, Jan Steggemann <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

Can you also transfer /Tau/Run2016D-PromptReco-v2/MINIAOD?

Thanks again,
Jan

PS: Looks like we should add another thread if these keep getting deleted very soon after completion...

https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=site+dataset%3D%2FTau%2FRun2016D-PromptReco-v2%2FMINIAOD

**Comment by safarzad** [comment]
Hi Marc,

I see some of files of this sample 
/SMS-T2cc_genHT-160_genMET-80_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16Fast_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

are already at CERN . Could you please let me know if do we need to make a transfer request for the rest of files or all files have been already copying to CERN?

Best,
Batool

**Comment by mdunser** [comment]
Hi Batool,

from what I can tell in phedex the dataset is subscribed and also fully transferred (DAS says the same).

-m

On 30 Jul 2016, at 12:06, safarzad <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

I see some of files of this sample
/SMS-T2cc_genHT-160_genMET-80_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16Fast_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

are already at CERN . Could you please let me know if do we need to make a transfer request for the rest of files or all files have been already copying to CERN?

Best,
Batool

**Comment by safarzad** [comment]
Hi Marc,

Could you please transfer this sample:

/TGJets_leptonDecays_scaledown_13TeV_amcatnlo_madspin_pythia8/RunIISpring16MiniAODv2-premix_withHLT_80X_mcRun2_asymptotic_v14-v1/MINIAODSIM

Best,
Batool

**Comment by mdunser** [comment]
here you go: https://cmsweb.cern.ch/phedex/prod/Request::View?request=769731
happy monday,
-m

On 29 Aug 2016, at 08:37, safarzad <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

Could you please transfer this sample:

/TGJets_leptonDecays_scaledown_13TeV_amcatnlo_madspin_pythia8/RunIISpring16MiniAODv2-premix_withHLT_80X_mcRun2_asymptotic_v14-v1/MINIAODSIM

Best,
Batool

**Comment by steggema** [comment]
Hi Marc,

Could you transfer the following datasets:
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_reHLT_80X_mcRun2_asymptotic_v14_ext1-v1/MINIAODSIM
/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

Thanks,
Jan

**Comment by mdunser** [comment]
Hi Jan,

here you go:
https://cmsweb.cern.ch/phedex/prod/Request::View?request=800566

Best,
-m

On 03 Oct 2016, at 09:51, Jan Steggemann <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

Could you transfer the following datasets:
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_reHLT_80X_mcRun2_asymptotic_v14_ext1-v1/MINIAODSIM
/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

Thanks,
Jan

**Comment by mariadalfonso** [comment]
Hi marc.
Can you transfer this one ?
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_reHLT_80X_mcRun2_asymptotic_v14-v1/MINIAODSIM

Thanks

**Comment by mdunser** [comment]
Hi Maria,

here you go: https://cmsweb.cern.ch/phedex/prod/Request::View?request=809406

-m

On 17 Oct 2016, at 15:09, mariadalfonso <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi marc.
Can you transfer this one ?
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_reHLT_80X_mcRun2_asymptotic_v14-v1/MINIAODSIM

Thanks

**Comment by mariadalfonso** [comment]
Hi marc.

Can you transfer this ?

/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-\
v1/MINIAODSIM

Maria

**Comment by mdunser** [comment]
Ciao Maria,

here’s the transfer request: https://cmsweb.cern.ch/phedex/prod/Request::View?request=816583

I doubt it will be approved before Monday though.

Have a delightful weekend,
-m

On 28 Oct 2016, at 18:12, mariadalfonso <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi marc.

Can you transfer this ?

/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-\
v1/MINIAODSIM

Maria

**Comment by steggema** [comment]
Hi Marc,

Would it be possible to transfer the following two samples to our buffer:

/GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIISpring16DR80-FlatPU20to70HcalNZSRAW_withHLT_80X_mcRun2_asymptotic_v14-v1/AODSIM
/GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIISpring16DR80-FlatPU20to70HcalNZSRAW_withHLT_80X_mcRun2_asymptotic_v14-v1/GEN-SIM-RAW

They're quite big (and not miniAOD), but I'll only need them for about 2 weeks and the sites that host them don't serve the data very efficiently.

Thanks,
Jan

**Comment by mdunser** [comment]
Hi Jan,

it turns out we have reached our 300 TB limit… I will have to come up with a list of stuff to delete before
we can continue with the transfers.
-m

On 10 Nov 2016, at 18:05, Jan Steggemann <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Marc,

Would it be possible to transfer the following two samples to our buffer:

/GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIISpring16DR80-FlatPU20to70HcalNZSRAW_withHLT_80X_mcRun2_asymptotic_v14-v1/AODSIM
/GluGluHToTauTau_M125_13TeV_powheg_pythia8/RunIISpring16DR80-FlatPU20to70HcalNZSRAW_withHLT_80X_mcRun2_asymptotic_v14-v1/GEN-SIM-RAW

They're quite big (and not miniAOD), but I'll only need them for about 2 weeks and the sites that host them don't serve the data very efficiently.

Thanks,
Jan

**Comment by mdunser** [comment]
Hi all,
here's some cleaning we'll have to do because of the filling up of the local buffer (it's at 300 TB right now).

We have most (or all) of the data, prompt and rereco in the local buffer, and we want to aim at keeping it this way. However, as of now we have some perhaps not very popular datasets which we could do without. So whoever is using the following datasets should speak up, otherwise they will be deleted:

/ZeroBias
/ParkingScoutingMonitor
/Commissioning
/Charmonium
/MuOnia
/HLTPhysics
/BTagCSV
/DisplacedJet
/HcalHPDNoise
/NoBPTX
/HcalNZS
/FSQJets
/L1MinimumBias

Additionally, these datasets:
/HighPtLowerJets/Run2015E-v1/RAW  
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIIFall15DR76-25nsFlat10to25TSG_HCALDebug_76X_mcRun2_asymptotic_v11-v1/GEN-SIM-RAW
/HighPtLowerJets/Run2015E-v1/RAW
/MinimumBias/Run2012A-v1/RAW#b0847904-85d5-11e1-a9bb-003048caaace

And _all_ 2015 datasets, especially the PromptReco ones.

Best,
-marc

**Comment by mariadalfonso** [comment]
Hi Marc.
can you transfer to CERN these ?

/WWW_4F_TuneCUETP8M1_13TeV-amcatnlo-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/WWZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/WZZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/ZZZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

/WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

Thanks

Maria

**Comment by mdunser** [comment]
Ciao Maria,

here’s the request: https://cmsweb.cern.ch/phedex/prod/Request::View?request=826498

Best,
-m

On 22 Nov 2016, at 10:01, mariadalfonso <notifications@github.com<mailto:notifications@github.com>> wrote:

/WWW_4F_TuneCUETP8M1_13TeV-amcatnlo-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/WWZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/WZZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM
/ZZZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

/WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM

**Comment by mdunser** [comment]
Dear all,

as I'll be going on a holiday tomorrow, I will not be able to make any phedex request from now to the 19th of December. If you have some very urgent requests, please send them now.

For requests between now and the 19th, there re a few options:

1) for heppy users, you can use AAA. This usually works in my experience, though failure rates might be higher.
2) crab
3) make the request yourself. 

For option 3): you can make a transfer request at this link
https://cmsweb.cern.ch/phedex/prod/Request::Create?type=xfer
just fill in the dataset name in the top box. Then select T2_CH_CERN in the "Destination" box. Then select "local" in the "User Group".

You can then look at the request by clicking Preview, or send it to the responsible admins by clicking Accept.

I will write an email to them asking to accept requests from people that aren't myself for the next few weeks .

So long,
-m
