### ISSUE TITLE
cmsIO not available anymore in default caf directory.

### ISSUE THREAD

**Issue by vischia** [CERN-PH-CMG/cmg-cmssw#699]
Hi, 

eostools makes use of /afs/cern.ch/cms/caf/python/cmsIO.py,

but the file is not available anymore at CERN.

Yesterday the directory has been emptied:
drwxr-xr-x. 6 22243 zh 2.0K Jun 12 11:25 python
and now cmsIO.py is in the
/afs/cern.ch/cms/caf/python.new
and also in
/afs/cern.ch/cms/caf/python.old

Does anyone know which are the caf software plans for that? I mean, can we expect that cmsIO will be put back in its place, or should we just update the path to it to /afs/cern.ch/cms/caf/python.new/ ?

Cheers,
Pietro

**Comment by gpetruc** [comment]
can you try https://github.com/CERN-PH-CMG/cmgtools-lite/pull/184 ?

**Comment by gpetruc** [comment]
should be fixed with  CERN-PH-CMG/cmgtools-lite#184 + #700.
reopen the issue if the fix doesn't work.
