### ISSUE TITLE
Support for AAA

### ISSUE THREAD

**Issue by gpetruc** [CERN-PH-CMG/cmg-cmssw#80]
We could possibly want to support the feature to read from anywhere via xrootd as per 
   https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookXrootdService
It's not fast, and one shouldn't abuse of the network it by running too many jobs reading from remote, but it can be useful for testing before samples are available at cern, or even for processing small samples (e.g. rare backgrounds or exotic signals)

**Comment by perrozzi** [comment]
ciao giovanni, I was trying to implement this feature. I was able to submit jobs, but noticed that all the jobs have been killed after 1h. Do you know if there could be any reason why?

**Comment by gpetruc** [comment]
I don't know, to me it worked, though painfully slow.

**Comment by perrozzi** [comment]
Could you please share your modifications, if possible?
I only rearranged a couple of lines to cope with the filename,
then used a personal grid certificate to create a voms to submit as suggested here
https://twiki.cern.ch/twiki/bin/viewauth/CMS/SUSYCMGfwk#How_to_run_if_you_are_external_t
I submitted from the cmgtools account though, I don't know if this may matter...
